apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: device-catalog
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: ""
  - name: keyPrefix
    value: "device-catalog"
